### ISSUE TITLE
Chromebooks

### ISSUE THREAD

**Issue by 3kh0** [AntiSmoothwall/Unblocked-Smoothwall-Games#3]
If you are on Chromebooks the game files crash. Is there a way to host it on the web?

**Comment by AntiSmoothwall** [comment]
it shouldn't. the download is just a text file with information and web links in it. might just be on a you problem.

**Comment by 3kh0** [comment]
then why did you go through with all of this useless stuff in making it look professional. It is just a txt file with links that are not to any website hosted on github.
